print("=====Indexing=====")
parrot = "Norwegian Blue"
print(parrot[3])
print(parrot[4])
print(parrot[9])
print(parrot[3])
print(parrot[6])
print(parrot[8])
print("===============")
print(parrot[-11])
print(parrot[-10])
print(parrot[-5])
print(parrot[-11])
print(parrot[-8])
print(parrot[-6])
print("===============")
print(parrot[3 - 14])
print(parrot[4 - 14])
print(parrot[9 - 14])
print(parrot[3 - 14])
print(parrot[6 - 14])
print(parrot[8 - 14])
print("=====Slicing=====")
print(parrot[0:6])
print(parrot[3:5])
print(parrot[0:9])
print(parrot[:9])
print(parrot[10:14])
print(parrot[10:])
print()
print(parrot[:6])
print(parrot[6:])
print(parrot[:6] + parrot[6:])
print(parrot[6:] + parrot[:6])
print(parrot[:])
print()
print("===Slicing with negative numbers===")
# letters = "abcdefghijklmnopqrstuvwxyz"

print(parrot[-4:-1])
print(parrot[-14:-8])
print("""===================""")
parrot = "Norwegian Blue"
print(parrot[0:6:2])
print(parrot[0:6:3])
print("""===================""")
numbers = "9,223;372:036 854,775;807"
seperators = numbers[1::4]
print(seperators)
values = "".join(char if char not in seperators else " " for char in numbers).split()
print(values)
print([int(val) for val in values])
